print("put 0V on Channel 1, enter Reading")
txt_zero_0 = input()
fl_zero_0 = float(txt_zero_0)
print("put 1V on Channel 1, enter Reading")
txt_one_0 = input()
fl_one_0 = float(txt_one_0)
print("put 0V on Channel 1, enter Reading")
txt_zero_0 = input()
fl_zero_0 = float(txt_zero_0)
print("put 1V on Channel 1, enter Reading")
txt_one_0 = input()
fl_one_0 = float(txt_one_0)